# Site settings
title: Matthew Archer
email: ma595@cam.ac.uk
description: "Matthew Archer"
url: "http://www.mattarcher.eu"
# twitter_username: js947
# github_username:  js947

# Build settings
markdown: kramdown
permalink: pretty
